/**
 * Traditional Chinese copies of the hand-written Simplified guide texts, converted with OpenCC
 * (cn -> twp, phrase-aware, so 公里 stays 公里 and 软件 becomes 軟體). The app uses these on
 * /zh-hant pages; the character-level map in hantChars.generated.ts is only for small UI labels.
 * Run: npx tsx scripts/gen-zh-hant-data.ts   (also runs in `npm run build`)
 */
import fs from "fs";
import path from "path";
// @ts-ignore — no types shipped
import * as OpenCC from "opencc-js";
import { blogPostsZh, areaGuidesZh, developerProfilesZh, CATEGORY_ZH, UI_ZH } from "../src/data/blog-data.zh";
import { buyingGuides } from "../src/data/buying-guides";

const toHant: (t: string) => string = (OpenCC as any).Converter({ from: "cn", to: "twp" });
// Links to the listing site follow the reader's script: /zh -> /zh-hant
const conv = (v: any): any => typeof v === "string" ? toHant(v).replace(/jbproperties\.my\/zh(\/|"|\))/g, "jbproperties.my/zh-hant$1") : Array.isArray(v) ? v.map(conv) : v && typeof v === "object" ? Object.fromEntries(Object.entries(v).map(([k, x]) => [k, conv(x)])) : v;

const out = {
  blogPostsHant: conv(blogPostsZh),
  areaGuidesHant: conv(areaGuidesZh),
  developerProfilesHant: conv(developerProfilesZh),
  categoryHant: conv(CATEGORY_ZH),
  uiHant: conv(UI_ZH),
  buyingGuidesHant: Object.fromEntries(buyingGuides.map((g) => [g.type, { label: toHant(g.label.ZH), title: toHant(g.title.ZH), intro: toHant(g.intro.ZH), sections: g.sections.map((s) => ({ heading: toHant(s.heading.ZH), body: toHant(s.body.ZH) })) }]))
};
const file = path.join(process.cwd(), "src", "data", "blog-data.zh-hant.generated.ts");
fs.writeFileSync(file, `// GENERATED by scripts/gen-zh-hant-data.ts from blog-data.zh.ts and buying-guides.ts — do not edit by hand.\n` +
  Object.entries(out).map(([k, v]) => `export const ${k}: any = ${JSON.stringify(v)};`).join("\n") + "\n", "utf8");
console.log(`[gen-zh-hant-data] ${Object.keys(out.blogPostsHant).length} articles, ${Object.keys(out.areaGuidesHant).length} areas, ${Object.keys(out.developerProfilesHant).length} developers, ${Object.keys(out.buyingGuidesHant).length} buyer guides -> ${path.relative(process.cwd(), file)}`);
