// GENERATED by scripts/gen-nearby-osm.ts from OpenStreetMap — do not edit by hand.
// Straight-line distance in km from the project's coordinates to the nearest named place of each
// kind. A walk or a drive is always longer; the page says so where it prints these.

export interface OsmPlace { category: string; categoryZh: string; name: string; km: number }

export const NEARBY_OSM: Record<string, OsmPlace[]> = {
 "aethera-residences": [
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "Bukit Chagar",
   "km": 0.4
  },
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "JB Sentral Bus Terminal",
   "km": 0.82
  },
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "Johor Bahru Sentral",
   "km": 0.83
  },
  {
   "category": "Border checkpoints",
   "categoryZh": "关卡",
   "name": "Johor Bahru",
   "km": 0.76
  },
  {
   "category": "Border checkpoints",
   "categoryZh": "关卡",
   "name": "Johor Bahru (motosikal dan basikal)",
   "km": 0.76
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Komtar JBCC",
   "km": 0.62
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "SKS Tower",
   "km": 0.68
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Danga City Mall",
   "km": 0.82
  },
  {
   "category": "Supermarkets",
   "categoryZh": "超市",
   "name": "M&S Outlet",
   "km": 0.64
  },
  {
   "category": "Supermarkets",
   "categoryZh": "超市",
   "name": "KNN Supermarket",
   "km": 0.86
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Sekolah Kebangsaan (P) Bandar Tinggi",
   "km": 0.17
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Sekolah Jenis Kebangsaan (C) St. Joseph dan Sekolah Kebangsaan St. Joseph",
   "km": 0.22
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Sekolah Sri Johor Bahru",
   "km": 0.29
  },
  {
   "category": "Hospitals and clinics",
   "categoryZh": "医院与诊所",
   "name": "Faizal Women Specialist Clinic",
   "km": 0.15
  },
  {
   "category": "Hospitals and clinics",
   "categoryZh": "医院与诊所",
   "name": "Teo Orthopaedic Specialist Clinic",
   "km": 0.16
  },
  {
   "category": "Parks",
   "categoryZh": "公园",
   "name": "Taman Istana Besar",
   "km": 1.06
  },
  {
   "category": "Parks",
   "categoryZh": "公园",
   "name": "Serene Park Community Park",
   "km": 1.58
  }
 ],
 "axis-tower": [
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "JB Sentral Bus Terminal",
   "km": 0.51
  },
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "Johor Bahru Sentral",
   "km": 0.53
  },
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "Bukit Chagar",
   "km": 0.87
  },
  {
   "category": "Border checkpoints",
   "categoryZh": "关卡",
   "name": "Johor Bahru (motosikal dan basikal)",
   "km": 0.25
  },
  {
   "category": "Border checkpoints",
   "categoryZh": "关卡",
   "name": "Johor Bahru",
   "km": 0.26
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Johor Bahru City Square",
   "km": 0.63
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Komtar JBCC",
   "km": 0.74
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Gallaria@Kotaraya",
   "km": 0.84
  },
  {
   "category": "Supermarkets",
   "categoryZh": "超市",
   "name": "Jaya Grocer",
   "km": 0.34
  },
  {
   "category": "Supermarkets",
   "categoryZh": "超市",
   "name": "KNN Supermarket",
   "km": 0.71
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Open University Malaysia",
   "km": 0.61
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Kolej Vokasional Tanjung Puteri",
   "km": 1
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Sekolah Menengah Teknik Tanjung Puteri Johor Bahru",
   "km": 1.01
  },
  {
   "category": "Hospitals and clinics",
   "categoryZh": "医院与诊所",
   "name": "Klinik Dr. Mahmud JB",
   "km": 0.82
  },
  {
   "category": "Hospitals and clinics",
   "categoryZh": "医院与诊所",
   "name": "Klinik Gan",
   "km": 1
  },
  {
   "category": "Parks",
   "categoryZh": "公园",
   "name": "Serene Park Community Park",
   "km": 0.96
  },
  {
   "category": "Parks",
   "categoryZh": "公园",
   "name": "Taman Istana Besar",
   "km": 1.6
  }
 ],
 "brixton-tower": [
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "JB Sentral Bus Terminal",
   "km": 0.46
  },
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "Johor Bahru Sentral",
   "km": 0.48
  },
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "Bukit Chagar",
   "km": 0.84
  },
  {
   "category": "Border checkpoints",
   "categoryZh": "关卡",
   "name": "Johor Bahru (lori)",
   "km": 0.22
  },
  {
   "category": "Border checkpoints",
   "categoryZh": "关卡",
   "name": "Johor Bahru (motosikal dan basikal)",
   "km": 0.24
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Johor Bahru City Square",
   "km": 0.57
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Komtar JBCC",
   "km": 0.69
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Gallaria@Kotaraya",
   "km": 0.78
  },
  {
   "category": "Supermarkets",
   "categoryZh": "超市",
   "name": "Jaya Grocer",
   "km": 0.32
  },
  {
   "category": "Supermarkets",
   "categoryZh": "超市",
   "name": "KNN Supermarket",
   "km": 0.65
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Open University Malaysia",
   "km": 0.67
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Unitar International University",
   "km": 0.99
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Kolej Vokasional Tanjung Puteri",
   "km": 1.02
  },
  {
   "category": "Hospitals and clinics",
   "categoryZh": "医院与诊所",
   "name": "Klinik Dr. Mahmud JB",
   "km": 0.76
  },
  {
   "category": "Hospitals and clinics",
   "categoryZh": "医院与诊所",
   "name": "KPJ Medical Suites",
   "km": 0.95
  },
  {
   "category": "Parks",
   "categoryZh": "公园",
   "name": "Serene Park Community Park",
   "km": 1.01
  },
  {
   "category": "Parks",
   "categoryZh": "公园",
   "name": "Taman Istana Besar",
   "km": 1.55
  }
 ],
 "dover-tower": [
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "JB Sentral Bus Terminal",
   "km": 0.37
  },
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "Johor Bahru Sentral",
   "km": 0.39
  },
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "Bukit Chagar",
   "km": 0.76
  },
  {
   "category": "Border checkpoints",
   "categoryZh": "关卡",
   "name": "Johor Bahru (lori)",
   "km": 0.13
  },
  {
   "category": "Border checkpoints",
   "categoryZh": "关卡",
   "name": "Johor Bahru (motosikal dan basikal)",
   "km": 0.21
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Johor Bahru City Square",
   "km": 0.47
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Komtar JBCC",
   "km": 0.6
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Gallaria@Kotaraya",
   "km": 0.69
  },
  {
   "category": "Supermarkets",
   "categoryZh": "超市",
   "name": "Jaya Grocer",
   "km": 0.34
  },
  {
   "category": "Supermarkets",
   "categoryZh": "超市",
   "name": "KNN Supermarket",
   "km": 0.55
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Open University Malaysia",
   "km": 0.77
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Unitar International University",
   "km": 0.91
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Sekolah Menengah Teknik Tanjung Puteri Johor Bahru",
   "km": 1.03
  },
  {
   "category": "Hospitals and clinics",
   "categoryZh": "医院与诊所",
   "name": "Klinik Dr. Mahmud JB",
   "km": 0.67
  },
  {
   "category": "Hospitals and clinics",
   "categoryZh": "医院与诊所",
   "name": "KPJ Medical Suites",
   "km": 0.86
  },
  {
   "category": "Parks",
   "categoryZh": "公园",
   "name": "Serene Park Community Park",
   "km": 1.08
  },
  {
   "category": "Parks",
   "categoryZh": "公园",
   "name": "Taman Istana Besar",
   "km": 1.45
  }
 ],
 "coronade-twins": [
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "Bukit Chagar",
   "km": 0.35
  },
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "Johor Bahru Sentral",
   "km": 0.52
  },
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "JB Sentral Bus Terminal",
   "km": 0.53
  },
  {
   "category": "Border checkpoints",
   "categoryZh": "关卡",
   "name": "Johor Bahru",
   "km": 0.57
  },
  {
   "category": "Border checkpoints",
   "categoryZh": "关卡",
   "name": "Johor Bahru (motosikal dan basikal)",
   "km": 0.61
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Komtar JBCC",
   "km": 0.3
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Johor Bahru City Square",
   "km": 0.5
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Gallaria@Kotaraya",
   "km": 0.58
  },
  {
   "category": "Supermarkets",
   "categoryZh": "超市",
   "name": "M&S Outlet",
   "km": 0.33
  },
  {
   "category": "Supermarkets",
   "categoryZh": "超市",
   "name": "KNN Supermarket",
   "km": 0.45
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Sekolah Jenis Kebangsaan (C) St. Joseph dan Sekolah Kebangsaan St. Joseph",
   "km": 0.27
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "SK Ayer Molek",
   "km": 0.33
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Sekolah Kebangsaan (P) Bandar Tinggi",
   "km": 0.35
  },
  {
   "category": "Hospitals and clinics",
   "categoryZh": "医院与诊所",
   "name": "KPJ Medical Suites",
   "km": 0.1
  },
  {
   "category": "Hospitals and clinics",
   "categoryZh": "医院与诊所",
   "name": "Klinik Gan",
   "km": 0.12
  },
  {
   "category": "Parks",
   "categoryZh": "公园",
   "name": "Taman Istana Besar",
   "km": 0.75
  },
  {
   "category": "Parks",
   "categoryZh": "公园",
   "name": "Serene Park Community Park",
   "km": 1.63
  }
 ],
 "gen-sphere": [
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "Johor Bahru Sentral",
   "km": 0.4
  },
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "JB Sentral Bus Terminal",
   "km": 0.4
  },
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "Bukit Chagar",
   "km": 0.83
  },
  {
   "category": "Border checkpoints",
   "categoryZh": "关卡",
   "name": "Johor Bahru (lori)",
   "km": 0.13
  },
  {
   "category": "Border checkpoints",
   "categoryZh": "关卡",
   "name": "Johor Bahru",
   "km": 0.37
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Johor Bahru City Square",
   "km": 0.42
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Gallaria@Kotaraya",
   "km": 0.57
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Komtar JBCC",
   "km": 0.62
  },
  {
   "category": "Supermarkets",
   "categoryZh": "超市",
   "name": "Jaya Grocer",
   "km": 0.27
  },
  {
   "category": "Supermarkets",
   "categoryZh": "超市",
   "name": "KNN Supermarket",
   "km": 0.49
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Unitar International University",
   "km": 0.75
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Open University Malaysia",
   "km": 0.86
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "SK Ayer Molek",
   "km": 1.08
  },
  {
   "category": "Hospitals and clinics",
   "categoryZh": "医院与诊所",
   "name": "Klinik Dr. Mahmud JB",
   "km": 0.64
  },
  {
   "category": "Hospitals and clinics",
   "categoryZh": "医院与诊所",
   "name": "KPJ Medical Suites",
   "km": 0.84
  },
  {
   "category": "Parks",
   "categoryZh": "公园",
   "name": "Serene Park Community Park",
   "km": 1.26
  },
  {
   "category": "Parks",
   "categoryZh": "公园",
   "name": "Taman Istana Besar",
   "km": 1.36
  }
 ],
 "m-grand-minori": [
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "Bukit Chagar",
   "km": 1.86
  },
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "JB Sentral Bus Terminal",
   "km": 1.96
  },
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "Johor Bahru Sentral",
   "km": 2
  },
  {
   "category": "Border checkpoints",
   "categoryZh": "关卡",
   "name": "Paragon Suites @ CIQ",
   "km": 1.2
  },
  {
   "category": "Border checkpoints",
   "categoryZh": "关卡",
   "name": "Pejabat Jabatan Kastam Diraja Malaysia",
   "km": 1.45
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Pelangi Leisure Mall",
   "km": 0.56
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Plaza Pelangi",
   "km": 0.91
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "SKS Tower",
   "km": 1.32
  },
  {
   "category": "Supermarkets",
   "categoryZh": "超市",
   "name": "Pasar Mini Lollipop",
   "km": 0.17
  },
  {
   "category": "Supermarkets",
   "categoryZh": "超市",
   "name": "Pasar Mini De Luxe Circle Fresh Mart",
   "km": 0.17
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Sekolah Agama Taman Pelangi",
   "km": 0.2
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Sekolah Menengah Kebangsaan Taman Pelangi",
   "km": 0.26
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Pusat Tuisyen Redang Bestari",
   "km": 0.35
  },
  {
   "category": "Hospitals and clinics",
   "categoryZh": "医院与诊所",
   "name": "Klinik Pakar Mata Tan Eye Surgery & Laser",
   "km": 0.16
  },
  {
   "category": "Hospitals and clinics",
   "categoryZh": "医院与诊所",
   "name": "Klinik Chen",
   "km": 0.19
  },
  {
   "category": "Parks",
   "categoryZh": "公园",
   "name": "Serene Park Community Park",
   "km": 0.84
  },
  {
   "category": "Parks",
   "categoryZh": "公园",
   "name": "Taman Istana Besar",
   "km": 2.95
  }
 ],
 "princess-cove-phase-2": [
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "Johor Bahru Sentral",
   "km": 0.91
  },
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "JB Sentral Bus Terminal",
   "km": 0.91
  },
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "Bukit Chagar",
   "km": 1.35
  },
  {
   "category": "Border checkpoints",
   "categoryZh": "关卡",
   "name": "Johor Bahru (lori)",
   "km": 0.65
  },
  {
   "category": "Border checkpoints",
   "categoryZh": "关卡",
   "name": "Johor Bahru (motosikal dan basikal)",
   "km": 0.83
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Johor Bahru City Square",
   "km": 0.89
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Gallaria@Kotaraya",
   "km": 0.93
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Komtar JBCC",
   "km": 1.12
  },
  {
   "category": "Supermarkets",
   "categoryZh": "超市",
   "name": "Jaya Grocer",
   "km": 0.28
  },
  {
   "category": "Supermarkets",
   "categoryZh": "超市",
   "name": "KNN Supermarket",
   "km": 0.95
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Open University Malaysia",
   "km": 0.79
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Unitar International University",
   "km": 0.92
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Sekolah Menengah Foon Yew",
   "km": 1.48
  },
  {
   "category": "Hospitals and clinics",
   "categoryZh": "医院与诊所",
   "name": "Klinik Dr. Mahmud JB",
   "km": 1.13
  },
  {
   "category": "Hospitals and clinics",
   "categoryZh": "医院与诊所",
   "name": "KPJ Medical Suites",
   "km": 1.32
  },
  {
   "category": "Parks",
   "categoryZh": "公园",
   "name": "Woodlands Waterfront Park",
   "km": 1.14
  },
  {
   "category": "Parks",
   "categoryZh": "公园",
   "name": "Serene Park Community Park",
   "km": 1.48
  }
 ],
 "princess-cove-phase-3": [
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "JB Sentral Bus Terminal",
   "km": 0.68
  },
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "Johor Bahru Sentral",
   "km": 0.69
  },
  {
   "category": "Train stations",
   "categoryZh": "轨道交通",
   "name": "Bukit Chagar",
   "km": 1.09
  },
  {
   "category": "Border checkpoints",
   "categoryZh": "关卡",
   "name": "Johor Bahru (lori)",
   "km": 0.43
  },
  {
   "category": "Border checkpoints",
   "categoryZh": "关卡",
   "name": "Johor Bahru (motosikal dan basikal)",
   "km": 0.51
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Johor Bahru City Square",
   "km": 0.73
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Gallaria@Kotaraya",
   "km": 0.87
  },
  {
   "category": "Shopping malls",
   "categoryZh": "商场",
   "name": "Komtar JBCC",
   "km": 0.91
  },
  {
   "category": "Supermarkets",
   "categoryZh": "超市",
   "name": "Jaya Grocer",
   "km": 0.12
  },
  {
   "category": "Supermarkets",
   "categoryZh": "超市",
   "name": "KNN Supermarket",
   "km": 0.8
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Open University Malaysia",
   "km": 0.58
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Unitar International University",
   "km": 0.99
  },
  {
   "category": "Schools and campuses",
   "categoryZh": "学校与大学",
   "name": "Sekolah Menengah Foon Yew",
   "km": 1.26
  },
  {
   "category": "Hospitals and clinics",
   "categoryZh": "医院与诊所",
   "name": "Klinik Dr. Mahmud JB",
   "km": 0.95
  },
  {
   "category": "Hospitals and clinics",
   "categoryZh": "医院与诊所",
   "name": "KPJ Medical Suites",
   "km": 1.15
  },
  {
   "category": "Parks",
   "categoryZh": "公园",
   "name": "Serene Park Community Park",
   "km": 1.15
  },
  {
   "category": "Parks",
   "categoryZh": "公园",
   "name": "Woodlands Waterfront Park",
   "km": 1.38
  }
 ]
};
